FROM php:7.4-fpm

LABEL maintainer='shmolf@gmail.com'

# If using for a production-like environment, uncomment the next line
# RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

EXPOSE 9000
CMD ["php-fpm"]
