account.create:
  path: /create
  controller: App\Controller\RegistrationController::form
  methods: GET

account.create.save:
  path: /create
  controller: App\Controller\RegistrationController::register
  methods: POST

account.edit:
  path: /
  controller: App\Controller\User\AccountController::edit
  methods: GET

account.edit.save:
  path: /edit
  controller: App\Controller\User\AccountController::save
  methods: POST
