yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "@semantic-release/commit-analyzer@*":
    peerDependenciesMeta:
      "conventional-changelog-conventionalchangelog":
        optional: true
