# Docker Config is based on: https://github.com/GhazanfarMir/dockercompose-laravel-nginx
version: "3.3"

services:
  nginx:
    container_name: noted-storage-nginx
    image: nginx:1.21.1
    ports:
      - "${WEB_PORT}:80"
      - "${SSL_PORT}:443"
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/config/self-sign-cert.crt:/etc/ssl/certs/self-sign-cert.crt
      - ./docker/nginx/config/self-gen.key:/etc/ssl/certs/self-gen.key
    networks:
      - noted-storage-net
    depends_on:
      - php
      - node

  php:
    container_name: noted-storage-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: shmolf/php-fpm:latest
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: ${DOCUMENT_ROOT}
    environment:
      - DATABASE_URL=${SYMFONY_DB_URL}
      - DATABASE_VERSION=${SYMFONY_DB_VERSION}
      - NOTED_HOST=${NOTED_HOST}
    networks:
      - noted-storage-net
    depends_on:
      - database
    # make 'database' a known service/host inside of 'php'
    links:
      - database

  node-template: &node-default
    image: node:lts-alpine3.15
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
    working_dir: ${DOCUMENT_ROOT}
    environment:
      - NODE_ENV=${NODE_ENV}
    entrypoint:
      - yarn
    command:
      - dev

  node:
    <<: *node-default
    container_name: noted-storage-node

  database:
    container_name: noted-storage-database
    image: mysql:8.0.25
    restart: always
    # https://dev.mysql.com/doc/mysql-linuxunix-excerpt/8.0/en/docker-mysql-more-topics.html
    command: [
      '--default-authentication-plugin=mysql_native_password',
      '--character-set-server=utf8mb4'
    ]
    volumes:
      - noted-storage-app:/var/lib/mysql
    hostname: mysql-container
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - noted-storage-net

networks:
  noted-storage-net:
    driver: "bridge"

volumes:
  noted-storage-app:
