account.oauth.app.list:
  path: /app/list
  controller: App\Controller\User\OAuthController::appTokenList
  methods: GET

account.oauth.app.new:
  path: /app
  controller: App\Controller\User\OAuthController::createAppToken
  methods: POST

account.oauth.app.delete:
  path: /app/{uuid}
  controller: App\Controller\User\OAuthController::deleteAppToken
  methods: DELETE
  requirements:
    uuid: '[a-fA-F0-9\-]+'

account.oauth.login:
  path: /login
  controller: App\Controller\SecurityController::oAuthLogin

account.oauth.login.success:
  path: /login/success
  controller: App\Controller\SecurityController::oAuthLoginSuccess
  methods: GET

account.oauth.login.old:
  path: /login-old
  controller: App\Controller\User\OAuthController::remoteLoginForm
  methods: GET
