#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home:
  path: /
  controller: App\Controller\WelcomeController

security:
  path: /security
  controller: App\Controller\SecurityController::index

login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
  # we don't need to specify a controller, since `security.yaml` identifies this route-key as logout, and does magic
